<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414123205 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE candidacy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, motivation_message TEXT NOT NULL, cv BYTEA NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_link VARCHAR(500) NOT NULL, status_id INT NOT NULL, mission_id INT NOT NULL, freelance_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D930569D6BF700BD ON candidacy (status_id)');
        $this->addSql('CREATE INDEX IDX_D930569DBE6CAE90 ON candidacy (mission_id)');
        $this->addSql('CREATE INDEX IDX_D930569DE8DF656B ON candidacy (freelance_id)');
        $this->addSql('CREATE TABLE candidacy_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_number VARCHAR(50) NOT NULL, amount_ht INT NOT NULL, amount_ttc INT NOT NULL, edition_date DATE NOT NULL, siretclient VARCHAR(14) NOT NULL, siretfreelance VARCHAR(14) NOT NULL, company_name_client VARCHAR(100) NOT NULL, company_name_freelance VARCHAR(100) NOT NULL, name_client VARCHAR(255) DEFAULT NULL, name_freelance VARCHAR(255) DEFAULT NULL, first_name_client VARCHAR(100) DEFAULT NULL, first_name_freelance VARCHAR(100) DEFAULT NULL, street_address_client VARCHAR(255) NOT NULL, street_address_freelance VARCHAR(255) NOT NULL, city_address_client VARCHAR(100) NOT NULL, city_address_freelance VARCHAR(100) NOT NULL, country_address_client VARCHAR(100) NOT NULL, country_address_freelance VARCHAR(100) NOT NULL, postal_code_address_client VARCHAR(10) NOT NULL, postal_code_address_freelance VARCHAR(10) NOT NULL, mission_name VARCHAR(150) NOT NULL, mission_id INT NOT NULL, freelance_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90651744BE6CAE90 ON invoice (mission_id)');
        $this->addSql('CREATE INDEX IDX_90651744E8DF656B ON invoice (freelance_id)');
        $this->addSql('CREATE INDEX IDX_9065174419EB6921 ON invoice (client_id)');
        $this->addSql('CREATE TABLE offre_mission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT NOT NULL, budget INT NOT NULL, deadline DATE NOT NULL, language VARCHAR(50) DEFAULT NULL, freelance_assigned BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, has_first_payment BOOLEAN NOT NULL, first_payment_value INT DEFAULT NULL, category_id INT NOT NULL, status_id INT NOT NULL, client_id INT NOT NULL, freelance_service_provider_id INT DEFAULT NULL, invoice_number_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3CBC811C12469DE2 ON offre_mission (category_id)');
        $this->addSql('CREATE INDEX IDX_3CBC811C6BF700BD ON offre_mission (status_id)');
        $this->addSql('CREATE INDEX IDX_3CBC811C19EB6921 ON offre_mission (client_id)');
        $this->addSql('CREATE INDEX IDX_3CBC811CA194140F ON offre_mission (freelance_service_provider_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3CBC811C550E2F8C ON offre_mission (invoice_number_id)');
        $this->addSql('CREATE TABLE offre_mission_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE time_registered (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time INT NOT NULL, registered_date DATE NOT NULL, freelance_id INT NOT NULL, mission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C364CD8DE8DF656B ON time_registered (freelance_id)');
        $this->addSql('CREATE INDEX IDX_C364CD8DBE6CAE90 ON time_registered (mission_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, company VARCHAR(100) DEFAULT NULL, siret VARCHAR(14) NOT NULL, subscription_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(10) NOT NULL, department VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE candidacy ADD CONSTRAINT FK_D930569D6BF700BD FOREIGN KEY (status_id) REFERENCES candidacy_status (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidacy ADD CONSTRAINT FK_D930569DBE6CAE90 FOREIGN KEY (mission_id) REFERENCES offre_mission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidacy ADD CONSTRAINT FK_D930569DE8DF656B FOREIGN KEY (freelance_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744BE6CAE90 FOREIGN KEY (mission_id) REFERENCES offre_mission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744E8DF656B FOREIGN KEY (freelance_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174419EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offre_mission ADD CONSTRAINT FK_3CBC811C12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offre_mission ADD CONSTRAINT FK_3CBC811C6BF700BD FOREIGN KEY (status_id) REFERENCES offre_mission_status (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offre_mission ADD CONSTRAINT FK_3CBC811C19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offre_mission ADD CONSTRAINT FK_3CBC811CA194140F FOREIGN KEY (freelance_service_provider_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE offre_mission ADD CONSTRAINT FK_3CBC811C550E2F8C FOREIGN KEY (invoice_number_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE time_registered ADD CONSTRAINT FK_C364CD8DE8DF656B FOREIGN KEY (freelance_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_registered ADD CONSTRAINT FK_C364CD8DBE6CAE90 FOREIGN KEY (mission_id) REFERENCES offre_mission (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE candidacy DROP CONSTRAINT FK_D930569D6BF700BD');
        $this->addSql('ALTER TABLE candidacy DROP CONSTRAINT FK_D930569DBE6CAE90');
        $this->addSql('ALTER TABLE candidacy DROP CONSTRAINT FK_D930569DE8DF656B');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744BE6CAE90');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744E8DF656B');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_9065174419EB6921');
        $this->addSql('ALTER TABLE offre_mission DROP CONSTRAINT FK_3CBC811C12469DE2');
        $this->addSql('ALTER TABLE offre_mission DROP CONSTRAINT FK_3CBC811C6BF700BD');
        $this->addSql('ALTER TABLE offre_mission DROP CONSTRAINT FK_3CBC811C19EB6921');
        $this->addSql('ALTER TABLE offre_mission DROP CONSTRAINT FK_3CBC811CA194140F');
        $this->addSql('ALTER TABLE offre_mission DROP CONSTRAINT FK_3CBC811C550E2F8C');
        $this->addSql('ALTER TABLE time_registered DROP CONSTRAINT FK_C364CD8DE8DF656B');
        $this->addSql('ALTER TABLE time_registered DROP CONSTRAINT FK_C364CD8DBE6CAE90');
        $this->addSql('DROP TABLE candidacy');
        $this->addSql('DROP TABLE candidacy_status');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE offre_mission');
        $this->addSql('DROP TABLE offre_mission_status');
        $this->addSql('DROP TABLE time_registered');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
